# Generated by Django 4.2.3 on 2023-07-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='join_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
